language: go

go:
  - 1.2

script:
  - go test -coverprofile=coverage.txt -covermode=count

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - sudo pip install codecov

after_success: codecov
